# .github/workflows/scrape.yml

name: Scrape Substack Search Results

on:
  repository_dispatch:
    types: [n8n-trigger]

jobs:
  scrape-and-return:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright library
        run: npm install playwright-core

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run Playwright and Scrape Data
        id: scrape_step 
        run: |
          scraped_json=$(node -e "
            const { chromium } = require('playwright-core');
            async function run() {
              const browser = await chromium.launch();
              const page = await browser.newPage();
              await page.goto('https://substack.com/search/banjercito?searching=all_posts', { waitUntil: 'domcontentloaded' });
              
              // --- THIS IS THE NEW LINE ---
              // Wait for the first post title to appear on the page
              await page.waitForSelector('[data-testid=\"post-preview-title\"]');

              // Now that we know the content is loaded, scrape all the titles
              const titles = await page.locator('[data-testid=\"post-preview-title\"]').allInnerTexts();
              await browser.close();

              return JSON.stringify(titles);
            }
            run().then(console.log);
          ")
          echo "scraped_json=$scraped_json" >> $GITHUB_OUTPUT

      - name: Send data to n8n
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"postTitles\": ${{ steps.scrape_step.outputs.scraped_json }} }" \
          "${{ secrets.N8N_WEBHOOK_URL }}"
