# .github/workflows/scrape.yml

name: Scrape Substack with Puppeteer

on:
  repository_dispatch:
    types: [n8n-trigger]

jobs:
  scrape-and-return:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Puppeteer & Stealth libraries
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Run Puppeteer and Scrape Data
        id: scrape_step 
        run: |
          scraped_json=$(node -e "
            const puppeteer = require('puppeteer-extra');
            const StealthPlugin = require('puppeteer-extra-plugin-stealth');
            puppeteer.use(StealthPlugin());

            async function run() {
              let browser;
              try {
                browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
                const page = await browser.newPage();
                
                await page.goto('https://substack.com/search/banjercito?searching=all_posts', { waitUntil: 'domcontentloaded' });
                
                await page.waitForSelector('[data-testid=\"post-preview-title\"]', { timeout: 45000 });

                // --- THIS IS THE CORRECTED LINE ---
                const titles = await page.$$eval('[data-testid=\"post-preview-title\"]', elements => elements.map(el => el.innerText));
                
                return JSON.stringify(titles);

              } catch (e) {
                console.error(e.name, e.message);
                return '[]';
              } finally {
                if (browser) {
                  await browser.close();
                }
              }
            }
            run().then(console.log);
          ")
          echo "scraped_json=$scraped_json" >> $GITHUB_OUTPUT

      - name: Send data to n8n
        run: |
          curl -X POST -H "Content-TYPE": "application/json" \
          -d "{\"postTitles\": ${{ steps.scrape_step.outputs.scraped_json }} }" \
          "${{ secrets.N8N_WEBHOOK_URL }}"
